CMakeLists.txt
=> cmake: remove the -Wall warning

README, README.md, src/enc.cc, src/sjpeg.h
This is convenient for C-biding of the C++ API, wrapping the delete[].
Good suggestion by github/magicgoose.
=> add SjpegFreeBuffer() C-call to release buffer.

examples/vjpeg.cc, man/vjpeg.1
use the 'return' key (\n) to show the alternate picture.
Has to have the same dimension than the source.
=> -alt option: specifies an alternate picture to display

examples/utils.cc
ICC profile has precedence over gamma value, though.
=> PNG decoder: handle gAMA chunk

examples/utils.cc
iCCP is usually seen in the trailing info, not the head_info
=> PNG decoding: simplify gAMA + iCCP handling

src/bit_writer.cc, src/bit_writer.h, src/enc.cc, src/sjpegi.h, src/yuv_convert.cc
can be useful in itself. No need to hide it in the .cc.
We'll split enc.cc, which is getting *way* too large.
Moved everything to the sjpeg namespace.
Also: removed DCHECK macro
Change-Id: Ib8d8bcb61de74cb05199f2bf78d8c107182b2676
=> expose the Encoder struct in the .h

src/dichotomy.cc, src/sjpegi.h
we don't need to optimize the Huffman table inside the loop, if
we're only targetting PSNR. We can do this after the search only.
+ preparing for a speed-up in ComputePSNR()
Change-Id: I2f2159c1997997aa4be131becbb9dcd9332e80e2
=> small speed-optim during PSNR search

src/dichotomy.cc, src/enc.cc, src/sjpegi.h
we don't need to do the full quantize/run_level coding.
We just need to evaluate the quantization error in one call.
-> between 30% and 2x faster option -psnr.
Change-Id: I15c004bce12d17d64ae82029598d4a8991f0e7e9
=> Optimize ComputePSNR()

examples/sjpeg.cc, man/sjpeg.1, src/dichotomy.cc, src/enc.cc, src/sjpeg.h, src/sjpegi.h
The interface object is 'SearchHook', with a default implementation.
It can be customize separately, and attached to the SjpegEncodeParam
to provide an alternate implementation.
new parameters: -qmin/-qmax/-tolerance
'min_psnr' parameter is removed.
=> extract the dichotomy search as plugin

examples/sjpeg.cc
If ALT_HOOK_CLASS is defined, the related class is plugged in
as a replacement for the default implementation.
Change-Id: I451ba87f7707aa78fda1ef3ca3fd43720f8d1ff0
=> Add possibility for using special dichotomy hook

src/enc.cc
(for backward compatibility)
Change-Id: Ia5ac2361dc8953d40f7c688be165e5ea81f5af7b
=> don't use trellis for method = 6

examples/sjpeg.cc, examples/vjpeg.cc, man/sjpeg.1, src/enc.cc, src/jpeg_tools.cc, src/sjpeg.h
-> values: SJPEG_YUV_420, SJPEG_YUV_444, SJPEG_YUV_SHARP, SJPEG_AUTO
This is preferable to magic constants.
also add the shortcuts -420 / -444 / -sharp to 'sjpeg'
Change-Id: Ibd308a18d9dfd99b087a7524816b3ad16e66f004
=> make yuv_mode a proper enum SjpegYUVMode.

README, examples/sjpeg.cc, examples/vjpeg.cc, man/sjpeg.1, src/enc.cc, src/jpeg_tools.cc, src/sjpeg.h, src/sjpegi.h, tests/test_png_jpg.sh
There's no particular reason to make it just an int.
+ Fix SjpegEstimateQuality (there was a missing kZigzag[])
Output is unchanged (for int values of quality)
Also: make 'reduction' parameter be a float too.
Change-Id: I86831552e57536ed193e11ce6ca123f8909b44f3
=> make 'quality' parameter be a float value

examples/vjpeg.cc
Some compiler didn't like it. Let's be explicit.
=> remove the reinterpret_cast to SjpegYUVMode.

src/dichotomy.cc
log() of large values seems to behave differently on ARM and x86
(at least arm64-v8a).
Change-Id: I3c528a702daa4807ccbef78beef97b5e81f2bdaa
=> make GetPSNR() be the same on ARM and x86

src/dichotomy.cc, src/enc.cc
The matrix satellite data were no recomputed for the final pass.
Also: apply min_quant_[] values systematically.
=> fix psnr-search loop

src/jpeg_tools.cc, src/sjpeg.h, tests/test_cmd.sh
SjpegEstimateQuality() need not take zigzag-ordered input any more.
+add test.
=> fix the zigzag rationale

examples/sjpeg.cc, src/dichotomy.cc, src/enc.cc, src/sjpeg.h, src/sjpegi.h
This is to directly set the quantization matrices, instead of taking the current
quant_[][] ones as min_quant_[].
+ add extra doc details
+ make some SjpegEncodeParam fields privates
Change-Id: I5701c0c7388c1484dd2d84b27d1bdcf2ec4f441d
=> add SjpegEncodeParam::SetMinQuantization()

Makefile
On MacOS, the warnings were:
'xxx' is deprecated: first deprecated in macOS 10.9 [-Wdeprecated-declarations]
=> GLUT: remove deprecated warnings for GLUT compile

src/headers.cc
wouldn't normally show, since we always reserve() more than needed,
but better be exact!
+ clarify the size calc for SOF and SOS
=> fix bug in data_size calculation for EXIF chunk

examples/sjpeg.cc, examples/vjpeg.cc, src/bit_writer.cc, src/bit_writer.h, src/dichotomy.cc, src/enc.cc, src/headers.cc, src/sjpeg.h, src/sjpegi.h
Implement some useful variants: MemorySink and StringSink (next: VectorSink)
+ Change the SjpegEncode() signature to take a string* instead of returning a string
Rationalize the Memory allocation: all internal buffers pass through
the Alloc() and Free() functions, so we can later track or limit allocation
traffic.
Protect all new[] with (std::nothrow) and catch the error.
+ polished the bit_writer.h/cc code.
TODO(after): move the ByteSink declaration to a public header (like: sjpeg.h) for exposure.
Change-Id: I6e1b3cee8f62af12e60a1e40b64e8e5e23102798
=> introduce generic ByteSink for outputting bytes

src/headers.cc
Change-Id: Ia59fea7976c2978bb3c7b9cef06849d05e4915d7
=> sjpeg: add a missing state validation in Flush()

src/bit_writer.cc, src/bit_writer.h, src/enc.cc, src/sjpeg.h, src/sjpegi.h
* add a MemoryManager interface for low-level malloc/free
* add a MemoryManager hook to SjpegEncodeParam, in case some special
allocator is needed (debugging, etc.)
* Move ByteSink to sjpeg.h
* abstract Sink<T> to take arbitrary container
* specialize for string and vector<>
* add some factories for string and vector<uint8_t> byte-sink, so the
implementation details can stay in bit_writer.[c,hh]
Change-Id: I527ac1542f02caf6a688260af122b731f3be1cfb
=> re-organize the interfaces with core-codec

src/bit_writer.h
(like the protocol said we should)
Change-Id: I7c4f8e59d2064c6980729f08c320a9fcf0a07df9
=> sjpeg-sink: call Reset() for good in case of error

examples/vjpeg.cc, src/jpeg_tools.cc, src/sjpegi.h
+ move these undocumented functions to sjpeg namespace
+ rationalize the score_8x8 use (it's not 7x7!)
Change-Id: I625e2fe4174bebd780d0df11a5f99d8a7b1dbd97
=> fix some errors in BlockRiskiness

src/enc.cc, src/sjpeg.h
search_hook/memory fields were not initialized.
Change-Id: I0cce22b5cdace8d110511a7a17ba6ce86da89c34
=> fix EncoderParam constructor

CMakeLists.txt, Makefile, examples/sjpeg.cc, examples/utils.cc, examples/utils.h, man/sjpeg.1, src/md5sum.h, tests/test_cmd.sh
To force-include some binary files as metadata.
Also:
* switch to C++-11
* add MD5Digest()   [will be useful later for Extended-XMP]
Change-Id: I517e5fd2ed1054947fdfd079b15878c1f1c986f1
=> Add -xmp / -exif / -icc options

CMakeLists.txt
Most system use lib64 to install libraries on 64 bits arch system.
=> Use ${LIB_INSTALL_DIR} to specify library installation dir

src/bit_writer.h, src/enc.cc
+ the sink::Reset() was not resetting pos_
+ we were not calling sink->Reset() at the beginning of the Encode() call.
This is convenient in the event one would want to re-use the same Sink object
over multiple Encode() calls.
Change-Id: I983f0ac17bd50aabd6eb3a1e9de1aae65664b739
=> small API fix:

appveyor.yml
Creates an AppVeyor configuration to build sjpeg with CMake and Visual Studio 2019 (MSVC) for the x64 and ARM64 platforms.
An example build can be [found here](https://ci.appveyor.com/project/EwoutH/sjpeg/builds/38824899). AppVeyor needs to be enabled on the [GitHub Marketplace](https://github.com/marketplace/appveyor).
Currently the Arm64 job fails. See #109.
=> CI: Create AppVeyor configuration

CMakeLists.txt
When using a vendored sjpeg, the `cpufeatures` target clashes with other `cpufeatures` targets.
Avoid this by adding a `-sjpeg` suffix.
This happens when building SDL_image with vendored libraries.
SDL_image has support for libjxl, which uses sjpeg as a 3rd party library.
(libwebp also provides a cpufeatures target)
=> cmake: fix target name collision with other cpufeatures library

.github/workflows/ci.yml
Adds a basic CI configuration using GitHub Actions which builds sjpeg:
- on Linux using CMake and GCC 10
- on macOS using CMake and AppleClang 12
- for Android using CMake and the Android NDK
This configuration uses GitHub Actions, which needs to be [activated here](https://github.com/webmproject/sjpeg/actions). An example build from my fork can be [seen here](https://github.com/EwoutH/sjpeg/actions/runs/775121110).
For Windows there is already an AppVeyor configuration, which was added in #110.
=> Add basic CI configuration for Linux, macOS and Android

CMakeLists.txt
This allows the users of the library to also compile the library and create target called utils.
=> Updates utils target to sjpeg-utils to avoid clashing with user's libs

src/dichotomy.cc
If the binary search did not find a best result in the last step, then the stored run levels are invalid and have to be regenerated.
=> Fix search-to-target-size mode.

CMakeLists.txt
This library relies on sjpeg::EncoderParam::ResetMetadata() when
SJPEG_HAVE_JPEG or SJPEG_HAVE_PNG are set. The header is included
unconditionally, so the dependency is treated the same.
Fixes undefined reference link errors to the function.
Thanks to @leleliu008 for the report and proposed fix.
Fixes #120.
=> CMakeLists: fix sjpeg-utils dependency

CMakeLists.txt
quiets a warning with newer CMake versions:
Compatibility with CMake < 2.8.12 will be removed from a future version
of CMake.
=> CMakeLists: bump minimum cmake version to 2.8.12

src/enc.cc
fixes TSan warnings:
Read of size 8 at 0x7f6c00f850e8 by thread T914:
#0 InitializeStaticPointers
#1 sjpeg::Encoder::Encoder(SjpegYUVMode, int, int, sjpeg::ByteSink*)
...
Previous write of size 8 at 0x7f6c00f850e8 by thread T875:
#0 InitializeStaticPointers
#1 sjpeg::Encoder::Encoder(SjpegYUVMode, int, int, sjpeg::ByteSink*)
=> InitializeStaticPointers: make init thread safe

src/enc.cc
This matches the other classes that derive from Encoder.
=> EncoderNV12: remove unused W_/H_ private members

src/fdct.cc
Large coefficients can cause an int16_t overflow in FDTC calculation on NEON.
The fix replaces the last unsafe butterfly operation with vector multiplication add/sub instructions with int32_t outputs.
Fixes #128
=> fdtc: Fix overflow on NEON

.github/workflows/ci.yml
Just pick up whatever version of gcc is installed. This fixes an issue
with ubuntu-latest where gcc-10/g++-10 are not installed.
=> ci.yml: remove explicit CC/CXX definition

examples/vjpeg.cc, src/yuv_convert.cc
replace `(void)` with `()`; use of this synonym is more common in C++
code.
=> {vjpeg,yuv_convert}.cc: normalize void param lists

src/sjpegi.h
This fixes the const declaration of `ALIGN_CST` which has an initial
value, but is not technically a definition. Instead constexpr (which
counts as a definition) is used. This fixes linker errors in some
situations.
PiperOrigin-RevId: 307131466
=> sjpegi.h,Encoder: mark static const member as constexpr

examples/utils.cc, examples/vjpeg.cc, src/bit_writer.h, src/jpeg_tools.cc
This is more in line with the Google C++ style guide and quiets some
clang-tidy warnings.
PiperOrigin-RevId: 424285717
=> Replace NULL and 0 with nullptr in C++ code

src/enc.cc
These classes are mostly end state and not derived from further.
=> enc.cc: mark some Encoder classes as final

src/enc.cc
This focuses on member variables used in branches within loops which are
constant through the loop's execution. This avoids a reload of the value
and may allow the compiler to extract the condition and split the loops.
=> enc.cc: extract member vars from loops
