webmproject/sjpeg

- CMakeLists.txt
- src/enc.cc
- src/jpeg_tools.cc
> fix some compilation and cmake warnings

- examples/sjpeg.cc
- src/enc.cc
- src/jpeg_tools.cc
- src/sjpeg.h
was only working for 8b matrices.
-> Changed the SjpegFindQuantizer() signature.
> fix DQT with 16b-precision quant matrix

- examples/sjpeg.cc
- examples/vjpeg.cc
- man/sjpeg.1
- man/vjpeg.1
- src/enc.cc
- src/sjpeg.h
New option is '-trellis' (trellis is off by default).
> add trellis-based optimization (method 7 and 8)

- examples/sjpeg.cc
also: warn if -r option is used on non-jpeg source.
> sjpeg: print reduction or quality factor info

- examples/vjpeg.cc
useful for comparing compression efficiency.
> alt pic: print file size as info

- examples/utils.cc
Just let the library do it!
This mostly reverts previous gamma fixes.
> PNG decoder: much simpler gamma correction handling

- examples/sjpeg.cc
- man/sjpeg.1
- man/vjpeg.1
- src/bit_writer.cc
- src/bit_writer.h
- src/enc.cc
- src/sjpeg.h
new options: -size <int>, -psnr <float>
also: -pass <int> and -min_psnr <float>
The dichotomy loop might have some weird corner cases
but should be a good starting point for now.
Change-Id: Iffe3c23ab844de3cbd770d31b0cb8187d0c02a4f
> internal dichotomy for target size or psnr

- Android.mk
- CMakeLists.txt
- Makefile
- src/dichotomy.cc
- src/enc.cc
- src/headers.cc
- src/sjpegi.h
new files: dichotomy.cc (all the -psnr and -size search)
and headers.cc (all the WriteXXX() chunk-writing functions)
Change-Id: I8c882144f761c29b8d40af9d9f13ad6ebbdf2e59
> move some code out of enc.cc

- examples/sjpeg.cc
- src/sjpeg.h
Change-Id: I44c38320488d837c2a9038f7b08facb4e5b4f854
> fix few style typos

- src/dichotomy.cc
- src/enc.cc
Change-Id: I196e544b3d7b96bbfd858747f53fdfd1a9748c81
> fix few typos

- src/dichotomy.cc
Patch by Haoran Man.
Change-Id: Ia43598475d8dba36ac37e5bd60fc23cb16d3b050
> Speed up search loop.

- src/dichotomy.cc
- src/sjpegi.h
Change-Id: I006ccc808dc2ebd6cdfee741db1570602a907f6f
> misc code reorg and fix for leak

- src/bit_writer.h
- src/enc.cc
> speed coding up by using tmp variable

- src/sjpegi.h
patch by Haoran Man
Change-Id: I746375d0a6f893d10157fcb7e1ffa4ddfcb337bc
> fix Android build

- src/enc.cc
- src/sjpeg.h
Change-Id: I4c05019747713c3cdc3d360a67d6caa7df73dcd0
> fix some typos and off alignments

- src/enc.cc
Change-Id: I6ef92f506e80b9817719393797b5b6399a1addec
> use consistent 'float' precision.

- examples/sjpeg.cc
- src/dichotomy.cc
This is purely informative.
Change-Id: I24368e325551baadfb5d249a502b2749db4ba7af
> search hook: store final values (q, size/PSNR)

- src/enc.cc
- src/sjpeg.h
+ some cleanup (nullptr instead of NULL, harmonize param names, ...)
Change-Id: Ia2b3a13cd4bec20e50b250185c09113f35ab037a
> SjpegEncode() version that returns a pointer instead of string

- src/colors_rgb.cc
16x16 blocks and 8x8 were having different constants, rounding was
slightly different, etc (mostly for historical reasons).
Now we settle everything for the formulae:
Y       = ( 19595 * r + 38469 * g +  7471 * b + HALF) >> FRAC
U - 128 = (-11059 * r - 21709 * g + 32768 * b + HALF) >> FRAC
V - 128 = ( 32768 * r - 27439 * g -  5329 * b + HALF) >> FRAC
> Harmonize the RGB->YUV conversion constants

- src/enc.cc
~20-30% faster search with -psnr
> implement QuantizeErrorNEON

- src/colors_rgb.cc
- src/sjpeg.h
> Neon update for rgb->yuv

- examples/sjpeg.cc
- examples/utils.cc
- examples/utils.h
- man/sjpeg.1
- tests/test_cmd.sh
This is useful for verification and debugging.
Add a -crc option to just print the checksum of the output.
> add GetCRC32() for checking metadata

- src/enc.cc
Change-Id: I5f805b7a1a948475734f6fc6e4e0da4e312ffc2d
> SinglePassScanOptimized(): fix memory leak in case of error

- src/bit_writer.cc
- src/bit_writer.h
- src/sjpeg.h
At the end, we can sometimes call Commit() with extra_size = 0
and in this case we should return NULL (which is valid, but
was signaling an error).
-> Update the protocol to return an error bool for good.
Change-Id: I86e112c5fff678a21fe9be594ff3da4a71d0b7d9
> sjpeg sink: change the Commit() protocol a bit

- src/enc.cc
- src/sjpeg.h
Change-Id: Ic86dcf0ca5291879205ce176878af92f24e105d3
> remove not-really-needed SetReduction(float) API

- tests/test_png_jpg.sh
Change-Id: I4ee35d7b7569fefa3ef94ffb36043b240ffbe41f
> add a bit more test-cases

- examples/sjpeg.cc
- src/dichotomy.cc
- src/sjpeg.h
This is informative, to gather how many passes were actually necessary before convergence.
Change-Id: I513ac712d39d4003234e80fae9f5e368f96806cf
> SearchHook: use a 'pass' field to track pass number

- AUTHORS
> add Haoran to AUTHORS

- README
- examples/sjpeg.cc
- examples/utils.cc
- examples/utils.h
- examples/vjpeg.cc
- src/dichotomy.cc
- src/enc.cc
- src/fdct.cc
- src/sjpeg.h
- src/sjpegi.h
rename SjpegEncodeParam to sjpeg::EncoderParam
rename SjpegEncode to sjpeg::Encode()
Change-Id: I3904ea5b8df32fe0153cf5037a1aaa33a9d11d8b
> move some API functions to sjpeg namespace

- examples/vjpeg.cc
Change-Id: I09fc4cdbe29e26e807744fb5254d49c981d714d1
> vjpeg: fix signature: SjpegEncode -> sjpeg::Encode

- src/enc.cc
Change-Id: I573aa60027d53d771c263693213e565ab0d0347b
> fix small typo

- Makefile
- src/colors_rgb.cc
- src/jpeg_tools.cc
- src/sjpegi.h
we were doing (a + bK)/255 instead of (a/255 + b/255 * K)
+ fix the Makefile
Change-Id: I115031d88afa033dad683e820b5924442c46a3ee
> fix the riskiness score used in 'vjpeg'

- examples/vjpeg.cc
Change-Id: I3a73564a997874edeba7a909dcd023bf8f8b4db2
> use cmath and std:: math functions

- examples/sjpeg.cc
- examples/vjpeg.cc
- src/colors_rgb.cc
- src/enc.cc
- src/headers.cc
- src/jpeg_tools.cc
- src/sjpeg.h
- src/sjpegi.h
- tests/test_cmd.sh
- tests/test_png_jpg.sh
+ new enum: SJPEG_YUV_400
+ some clean-up
+ sjpeg's new option: -gray (or: -yuv_mode 4)
+ updated Riskiness to evaluate 'gray-ness'
> add YUV400 support (grayscale coding)

- CMakeLists.txt
<type> comes before <docstring>
> CMakeLists.txt: fix set(CACHE) argument order

- src/enc.cc
- src/sjpeg.h
These count as 'specialized' functions, that we don't necessarily want to publicize too much.
Change-Id: Ifcf58ddb1b62abf59b7769af0db3da708fada92a
> add EncodeGray() methods for encoding single luma-plane

- examples/utils.cc
- src/dichotomy.cc
- src/enc.cc
- src/headers.cc
- src/sjpeg.h
- src/sjpegi.h
The spec is here (section 1.1.3.1):
https://wwwimages2.adobe.com/content/dam/acom/en/devnet/xmp/pdfs/XMP%20SDK%20Release%20cc-2016-08/XMPSpecificationPart3.pdf
+ misc clean-up
Change-Id: I40aa21f90fe220ebec5b42fcc081b63c198c91f2
> implement XMPExtended metadata writing + reading

- src/colors_rgb.cc
- src/enc.cc
- src/sjpeg.h
- src/sjpegi.h
New functions: EncodeNV21(), EncodeYUV444(), EncodeYUV420()
+ some clean-up and refactoring
Change-Id: Ie760f7f465498f19b5725cec64c67562332758f7
> add support for NV21 and raw YUV-input encoding

- CMakeLists.txt
> CMake: use GNUInstallDirs

- src/enc.cc
- src/sjpeg.h
New function is EncodeNV12(), similar to EncodeNV21().
+ cosmetics
Change-Id: I101df8e372678f1d921fe06c8c7c4623fb87b3c5
> add support for EncoderNV12 encoding

- CMakeLists.txt
- Makefile
- README
- README.md
- cmake/cpu.cmake
- tests/test_cmd.sh
- tests/test_png_jpg.sh
+ add missing copyright headers
+ fix README.md formatting
Change-Id: Ic01e0c4d16131db287b503c6bab99fa02f1d2e7f
> CMake: add android build config

- Makefile
- cmake/android.cmake
* add appveyor.yml file to Makefile
* add missing android.cmake file (from #107)
Change-Id: Idd5b816f76a0f5eae0e4640c64cc58c7f8195143
> misc fixes

- src/enc.cc
- src/sjpegi.h
`DesallocateBlocks` -> `DeallocateBlocks`
> cosmetics: fix a typo
